### ISSUE TITLE
RE: Valheim's default value for "DSP Buffer Size" is 1024 but "SampleRate=0"

### ISSUE THREAD

**Issue by l1m3r** [AzumattDev/SimpleAudioOptions#1]
`> Also, I'm not fully aware or could find out what the defaults for Valheim were`

According to the file `\SteamApps\common\Valheim\valheim_Data\globalgamemanagers` some defaults are:

```
float Doppler Factor = 1
Default Speaker Mode = 2
m_SampleRate         = 0
m_DSPBufferSize      = 1024
m_VirtualVoiceCount  = 512
m_RealVoiceCount     = 32
m_VirtualizeEffects  = true
m_RequestedDSPBufferSize = 0
```

You can open/edit it with eg. [UABEA](https://github.com/nesrak1/UABEA)

My guess is that `m_SampleRate = 0` means VH/unity selects the system default (for the primary audio device). Which may be better than a fixed value different from that default, I think.

Btw. here is [my non-mod](https://github.com/l1m3r/cmd-scripts/tree/master/ss4vh) to enable surround sound, switch the keyboard input mode and add some entries to `\Valheim\valheim_Data\boot.config`.

PS: Out of curiosity - did you stumble over my script before you wrote this mod? What triggered/motivated you to write it? Was it the missing surround sound support in VH?

**Comment by AzumattDev** [comment]
I wrote the mod out of request in my discord. No, never heard of you or seen your script. I allowed changing the values but didn't care what Valheim defaults were, partially because I had no clue where to look to find them. Simply changing things in code like I always do.
